version: 2.1

executors:
  gfortran:
    machine:
      image: ubuntu-2004:202104-01
    environment:
      MY_VERSION: "20.04"
     
  ifort:
    machine:
      image: ubuntu-1604:202104-01
    environment:
      MY_VERSION: "16.04"
      
jobs:
  build-MAPL:
    parameters:
      compiler:
        description: Compile for this architecture
        type: executor
      
    executor: << parameters.compiler >>
    
    steps:
      - run:
          name: Check Ubuntu version
          command:|
            lsb_release -a
            echo "My Ubuntu is" $MY_VERSION
        
workflows:
  execmess:
    jobs:
      - build-MAPL:
          name: build-MAPL-<< matrix.compiler >>
          matrix:
            parameters:
              compiler: [gfortran, ifort]
