version: 2.1

executors:
  gfortran:
    machine:
      image: ubuntu-2004:202104-01
    environment:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1  
     
  ifort:
    machine:
      image: ubuntu-1604:202104-01
      
jobs:
  build-MAPL:
    parameters:
      compiler:
        description: Compile for this architecture
        type: executor
      
    executor: << parameters.compiler >>
    
    steps:
      - run:
          name: Check Ubuntu version
          command: lsb_release -a
        
workflows:
  execmess:
    jobs:
      - build-MAPL:
          name: build-MAPL-<< matrix.compiler >>
          matrix:
            parameters:
              compiler: [gfortran, ifort]
