version: 2

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum1
                   
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2
  
  daily:
    jobs:
      - premier

  sync:
    triggers:
      - schedule:
          cron: "50 16 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - deuxieme
      
  thirdly:
    triggers:
      - schedule:
          cron: "55 14 * * *"
          filters:
              branches:
                only:
                  - cheekycheck
    jobs:
      - troisieme
