version: 2.1

references:
  defaults: &defaults
    working_directory: ~/project
    docker:
      - image: python:3.6.1
    # steps:
    # - checkout

  interpolate_environment_variables: &interpolate_environment_variables
      run:
        name: Interpolate Environment Variables
        command: |
          echo 'set -o allexport' >> ${BASH_ENV}
          echo 'ROK8S_INSTALL_PATH=${HOME}/rok8s-scripts' >> ${BASH_ENV}
          echo 'PATH=$PATH:${HOME}/google-cloud-sdk/bin:node_modules/.bin:${HOME}/rs-scripts' >> ${BASH_ENV}
          echo 'CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
          echo 'CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
          echo 'CI_BUILD_NUM=$CIRCLE_BUILD_NUM' >> ${BASH_ENV}
          echo 'CI_TAG=$CIRCLE_TAG' >> ${BASH_ENV}
          echo 'PREVIOUS_COMMIT=$(git rev-parse HEAD~1)' >> ${BASH_ENV}
          echo 'REPOSITORY_NAME=$DOCKERTAG' >> ${BASH_ENV}
          echo 'NGINX_REPO_NAME=nginx-assets' >> ${BASH_ENV}
          echo 'POSTGRES_DB=$DATABASE_NAME' >> ${BASH_ENV}
          echo 'POSTGRES_USER=$DATABASE_USERNAME' >> ${BASH_ENV}
          echo 'set +o allexport' >> ${BASH_ENV}

  # deploy_steps: &deploy_steps
    # steps:
    # - checkout
    # - *defaults

jobs:
  test:
    <<: *defaults
    steps:
      - *interpolate_environment_variables

  test_2:
    <<: *defaults
    steps:
      - <<: *interpolate_environment_variables

workflows:
  letest:
    jobs:
      - test
      - test_2
