version: 2.1

jobs:
  lint:
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo Hello
    
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum1
                   
      - add_ssh_keys:
          fingerprints:
            - "07:39:a0:c9:ee:e9:59:4f:6d:1a:4e:0d:c9:af:44:ca"
                   
  deuxieme:
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum2
                   echo << parameters.saywhat >>
 
  troisieme:
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                   echo $saywhat
                                     
workflows:
  version: 2
  
  daily:
    jobs:
      - lint:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - premier:
          # <<: *after-linter
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
     

  sync:
    jobs:
      - deuxieme
      
  thirdly:
    triggers:
      - schedule:
          cron: "55 14 * * *"
          filters:
              branches:
                only:
                  - cheekycheck
    jobs:
      - troisieme
