version: 2.1

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum1
                   
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2.1
  daily:
    triggers:
      - schedule:
          cron: "04 11 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - premier

  sync:
  triggers:
      - schedule:
          cron: "20 11 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - deuxieme
      
  thirdly:
  triggers:
      - schedule:
          cron: "40 11 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - troisieme
