version: 2.1

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum1
                   
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
version: 2

  daily:
    triggers:
      - schedule:
          cron: "30 11 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - premier

  sync:
    triggers:
      - schedule:
          cron: "35 11 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - deuxieme
      
  daily:
    triggers:
      - schedule:
          cron: "40 11 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - troisieme
