version: 2.1

parameters:
  run_pull_request:
    default: false
    type: boolean
    
only_on_cheekycheck: &only_on_master
  filters:
    branches:
      only: master
    
jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum1
                   
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2
  
  daily:
    unless: <<pipeline.parameters.run_pull_request>>
    #jobs:
    #  - premier
    triggers:
      - schedule:
          cron: "42 14 * * *"
          <<: *only_on_master
         # filters:
         #     branches:
         #       only:
         #         - cheekycheck
         ##### Will it re-schedule??
    jobs:
      - premier
                
                  
  sync:
    triggers:
     # - schedule:
     #     cron: "50 16 * * *"
     #     filters:
     #         branches:
     #           only:
     #             - master
    jobs:
      - deuxieme:
          filters:
            branches:
              only:
                - master
      
  thirdly:
    jobs:
      - troisieme
